"""Fontes citadas nas páginas. Cada chave vira um número na página que a usa.
Só entram URLs abertas durante a verificação (conselho 2 e checagem de fatos, set/2026)."""

F = {
    # --- gasto público e método ---
    'ts2000': ('Tanzi e Schuknecht, Public Spending in the 20th Century, Tabela I.1 (Cambridge, 2000)',
               'https://catdir.loc.gov/catdir/samples/cam032/99040258.pdf'),
    'imf-wp95': ('Tanzi e Schuknecht, The Growth of Government and the Reform of the State in Industrial Countries (FMI, WP/95/130)',
                 'https://www.elibrary.imf.org/view/journals/001/1995/130/article-A001-en.xml'),
    'owid-gasto': ('Our World in Data: gasto público em % do PIB (dados do FMI, Public Finances in Modern History)',
                   'https://ourworldindata.org/grapher/historical-gov-spending-gdp'),
    'oecd-eo': ('OCDE, Economic Outlook 119: gasto total do governo geral',
                'https://sdmx.oecd.org/public/rest/data/OECD.ECO.MAD,DSD_EO@DF_EO,/OECD.YPGTQ.A?startPeriod=2000&endPeriod=2010&format=jsondata'),

    # --- 1: Irlanda, De Valera ---
    'ie-precos': ('Control of Prices Act 1937, Irish Statute Book', 'https://www.irishstatutebook.ie/eli/1937/act/26/enacted/en/html'),
    'ie-dib': ('Dictionary of Irish Biography: Éamon de Valera', 'https://www.dib.ie/biography/de-valera-eamon-dev-a2472'),
    'ie-cla35': ('Criminal Law Amendment Act 1935, seção 17, Irish Statute Book', 'https://www.irishstatutebook.ie/eli/1935/act/6/section/17/enacted/en/html'),
    'ie-bill34': ('Criminal Law Amendment Bill 1934, Oireachtas', 'https://www.oireachtas.ie/en/bills/bill/1934/31/'),
    'ie-const': ('Constituição da Irlanda de 1937, Irish Statute Book', 'https://www.irishstatutebook.ie/eli/cons/en/html'),
    'ie-exec': ('The Irish Story: as execuções de membros do IRA, 1940-1944',
                'https://www.theirishstory.com/2021/04/12/they-were-determined-to-obtain-a-sacrifice-first-irish-state-executions-of-ira-members-since-the-civil-war/'),
    'ie-contra': ('Contraception in the Republic of Ireland, Wikipedia', 'https://en.wikipedia.org/wiki/Contraception_in_the_Republic_of_Ireland'),

    # --- 2: EUA, Reagan ---
    'us-eo12287': ('Ordem Executiva 12287 (28/jan/1981), Arquivos Nacionais dos EUA', 'https://www.archives.gov/federal-register/codification/executive-order/12287.html'),
    'us-conrail': ('Conrail, Wikipedia', 'https://en.wikipedia.org/wiki/Conrail'),
    'us-eaa': ('Reagan, declaração ao sancionar a Education for Economic Security Act (1984)',
               'https://www.presidency.ucsb.edu/documents/statement-signing-the-education-for-economic-security-act'),
    'us-bowen': ('Bowen v. Kendrick (1988), Cornell LII', 'https://www.law.cornell.edu/supremecourt/text/487/589'),
    'us-rea': ('Reagan, declaração ao sancionar a Retirement Equity Act (1984)',
               'https://www.presidency.ucsb.edu/documents/statement-signing-the-retirement-equity-act-1984'),
    'us-irancontras': ('Iran-Contra affair, Wikipedia', 'https://en.wikipedia.org/wiki/Iran%E2%80%93Contra_affair'),
    'us-granada': ('Estado-Maior Conjunto dos EUA, Operation Urgent Fury (história oficial)',
                   'https://www.jcs.mil/Portals/36/Documents/History/Monographs/Urgent_Fury.pdf'),
    'us-libia86': ('Força Aérea dos EUA, Operation El Dorado Canyon', 'https://www.afhistory.af.mil/FAQs/Fact-Sheets/Article/458950/operation-el-dorado-canyon/'),
    'us-contras': ('Contras, Wikipedia', 'https://en.wikipedia.org/wiki/Contras'),

    # --- 2: Austrália, Howard ---
    'au-telstra': ('Telstra, Wikipedia', 'https://en.wikipedia.org/wiki/Telstra'),
    'au-tesouro': ('Tesouro da Austrália: a arquitetura do sistema de impostos e transferências',
                   'https://treasury.gov.au/sites/default/files/2019-10/afts_architecture_of_australias_tax_and_transfer_system_revised.pdf'),
    'au-howard': ('John Howard, Wikipedia', 'https://en.wikipedia.org/wiki/John_Howard'),
    'au-nt': ('Northern Territory National Emergency Response, Wikipedia', 'https://en.wikipedia.org/wiki/Northern_Territory_National_Emergency_Response'),
    'au-casamento': ('Marriage Amendment Act 2004, Wikipedia', 'https://en.wikipedia.org/wiki/Marriage_Amendment_Act_2004'),
    'iq-mortes': ('Casualties of the Iraq War, Wikipedia (IFHS/OMS 2008, Lancet 2006)', 'https://en.wikipedia.org/wiki/Casualties_of_the_Iraq_War'),
    'iq-ibc': ('Iraq Body Count', 'https://www.iraqbodycount.org/database/'),

    # --- 3: Suécia, Palme ---
    'se-precos': ('Governo da Suécia, SOU 2009:3: racionamento e regulação de preços',
                  'https://www.regeringen.se/contentassets/e59ddfc2f5ca49f7b428f42a1791868c/ransonering-och-prisreglering-i-krig-och-fred-sou-20093/'),
    'se-estatais': ('Governo da Suécia: a propriedade estatal no período moderno',
                    'https://www.regeringen.se/regeringens-politik/bolag-med-statligt-agande/statligt-agande-i-modern-tid/'),
    'se-cee': ('Riksdagen: acordo entre a Suécia e a CEE (SFS 1972:698)',
               'https://www.riksdagen.se/sv/dokument-och-lagar/dokument/svensk-forfattningssamling/kungorelse-1972698-om-avtalet-mellansverige_sfs-1972-698/'),
    'se-lindbeck': ('Assar Lindbeck, Swedish Economic Growth', 'http://perseus.iies.su.se/~alind/Links/Sw_Ec_Growth_SEPR.pdf'),
    'se-palme': ('Palme I cabinet, Wikipedia', 'https://en.wikipedia.org/wiki/Palme_I_cabinet'),
    'se-ib': ('IB affair, Wikipedia', 'https://en.wikipedia.org/wiki/IB_affair'),
    'se-divorcio': ('Proposição 1973:32 (divórcio), lagen.nu', 'https://lagen.nu/prop/1973:32'),
    'se-aborto': ('Proposição 1974:70 (aborto), Riksdagen',
                  'https://www.riksdagen.se/sv/dokument-och-lagar/dokument/proposition/kungl-majts-proposition-med-forslag-till_fx0370/html/'),
    'se-sexo': ('Diretiva 2006:8 sobre a lei 1972:119 (mudança de sexo), lagen.nu', 'https://lagen.nu/dir/2006:8'),

    # --- 3: Índia, Nehru ---
    'in-airindia': ('Air India, Wikipedia', 'https://en.wikipedia.org/wiki/Air_India'),
    'in-sbi': ('State Bank of India, Wikipedia', 'https://en.wikipedia.org/wiki/State_Bank_of_India'),
    'in-lic': ('Life Insurance Corporation, Wikipedia', 'https://en.wikipedia.org/wiki/Life_Insurance_Corporation'),
    'in-licenca': ('Licence Raj, Wikipedia', 'https://en.wikipedia.org/wiki/Licence_Raj'),
    'in-eca': ('Essential Commodities Act 1955, Wikipedia', 'https://en.wikipedia.org/wiki/Essential_Commodities_Act,_1955'),
    'in-nehru': ('Jawaharlal Nehru, Wikipedia', 'https://en.wikipedia.org/wiki/Jawaharlal_Nehru'),
    'in-kerala': ('Vimochana Samaram, Wikipedia', 'https://en.wikipedia.org/wiki/Vimochana_Samaram'),
    'in-codigo': ('Hindu code bills, Wikipedia', 'https://en.wikipedia.org/wiki/Hindu_code_bills'),
    'in-sma': ('Special Marriage Act 1954, Wikipedia', 'https://en.wikipedia.org/wiki/Special_Marriage_Act,_1954'),
    'in-hsa': ('Hindu Succession Act 1956, Wikipedia', 'https://en.wikipedia.org/wiki/Hindu_Succession_Act,_1956'),
    'in-hyderabad': ('Annexation of Hyderabad, Wikipedia (Comitê Sunderlal)', 'https://en.wikipedia.org/wiki/Annexation_of_Hyderabad'),
    'in-goa': ('Annexation of Goa, Wikipedia', 'https://en.wikipedia.org/wiki/Annexation_of_Goa'),
    'in-telangana': ('Telangana Rebellion, Wikipedia', 'https://en.wikipedia.org/wiki/Telangana_Rebellion'),

    # --- 3: Argentina, Alfonsín ---
    'ar-austral': ('Governo argentino: 14 de junho de 1985, lançamento do Plano Austral',
                   'https://www.argentina.gob.ar/noticias/14-de-junio-de-1985-lanzamiento-del-plan-austral'),
    'ar-porto': ('Alberto Porto, Evolución del sector público argentino (UNLP)',
                 'https://www.mfp.econo.unlp.edu.ar/wp-content/uploads/2021/08/EVOLUCION-del-sector-publico-arg-PORTO-WEB.pdf'),
    'ar-privat': ('Teseo Press: a experiência argentina de privatizações',
                  'https://www.teseopress.com/configuracion/chapter/2-la-experiencia-argentina-principales-caracteristicas-de-la-politica-de-privatizaciones-y-de-regulacion-de-los-servicios-publicos-domiciliarios-de-redfootnote-como-se-dejara-planteado-en-la-intro/'),
    'ar-juntas': ('Trial of the Juntas, Wikipedia', 'https://en.wikipedia.org/wiki/Trial_of_the_Juntas'),
    'ar-alfonsin': ('Raúl Alfonsín, Wikipedia', 'https://en.wikipedia.org/wiki/Ra%C3%BAl_Alfons%C3%ADn'),
    'ar-leis': ('La Nación: cronologia e texto das leis de Ponto Final e Obediência Devida',
                'https://www.lanacion.com.ar/politica/cronologia-y-texto-completo-de-las-leyes-nid712690/'),
    'ar-divorcio': ('Ley de divorcio vincular, Wikipedia', 'https://es.wikipedia.org/wiki/Ley_de_divorcio_vincular'),
    'ar-haroldo': ('Revista Haroldo: o caso Sejean e a lei do divórcio', 'https://revistaharoldo.com.ar/nota.php?id=738'),
    'ar-cedaw': ('Lei 23.179 (ratificação da CEDAW), governo argentino', 'https://www.argentina.gob.ar/normativa/nacional/ley-23179-26305'),
    'ar-tablada': ('CIDH, Informe 55/97 (La Tablada)', 'https://hrlibrary.umn.edu/cases/1997/Sargentina55-97c.html'),

    # --- 4: Nova Zelândia, Lange ---
    'nz-dolar': ('New Zealand dollar, Wikipedia', 'https://en.wikipedia.org/wiki/New_Zealand_dollar'),
    'nz-rogernomics': ('Rogernomics, Wikipedia', 'https://en.wikipedia.org/wiki/Rogernomics'),
    'nz-aco': ('New Zealand Steel, Wikipedia', 'https://en.wikipedia.org/wiki/New_Zealand_Steel'),
    'nz-air': ('Air New Zealand, Wikipedia', 'https://en.wikipedia.org/wiki/Air_New_Zealand'),
    'nz-lange': ('David Lange, Wikipedia', 'https://en.wikipedia.org/wiki/David_Lange'),
    'nz-hlr': ('NZHistory: a reforma da lei sobre homossexualidade passa na terceira leitura',
               'https://nzhistory.govt.nz/homosexual-law-reform-bill-passes-its-third-reading'),
    'nz-hansard': ('Hansard da Nova Zelândia, 9/jul/1986 (PrideNZ)',
                   'https://www.pridenz.com/hansard_homosexual_law_reform_bill_third_reading_continued_9_july_1986.html'),

    # --- 4: Chile, Lagos ---
    'cl-eua': ('Subrei: acordo de livre comércio Chile-EUA', 'https://www.subrei.gob.cl/acuerdos-comerciales/acuerdos-comerciales-vigentes/ee-uu'),
    'cl-ue': ('Subrei: acordo Chile-União Europeia', 'https://www.subrei.gob.cl/acuerdos-comerciales/acuerdos-comerciales-vigentes/union-europea'),
    'cl-auge': ('Plan AUGE, Wikipedia', 'https://es.wikipedia.org/wiki/Plan_AUGE'),
    'cl-lagos': ('Ricardo Lagos, Wikipedia', 'https://en.wikipedia.org/wiki/Ricardo_Lagos'),
    'hrw-chile': ('Human Rights Watch, Undue Process (2004)', 'https://www.hrw.org/reports/2004/chile1004/'),
    'cl-divorcio': ('Senado do Chile: tramitação do boletim 1759-18 (Lei 19.947)', 'https://tramitacion.senado.cl/wspublico/tramitacion.php?boletin=1759'),
    'cl-violencia': ('Senado do Chile: tramitação do boletim 2318-18 (Lei 20.066)', 'https://tramitacion.senado.cl/wspublico/tramitacion.php?boletin=2318'),

    # --- 4: EUA, Obama ---
    'us-gm': ('Tesouro dos EUA: programas automotivos do TARP', 'https://home.treasury.gov/data/troubled-assets-relief-program/automotive-programs/overview'),
    'us-pneus': ('PIIE: a tarifa sobre pneus chineses', 'https://www.piie.com/publications/policy-briefs/us-tire-tariffs-saving-few-jobs-high-cost'),
    'us-fhfa': ('FHFA: a tutela da Fannie Mae e da Freddie Mac', 'https://www.fhfa.gov/conservatorship'),
    'us-cpj': ('CPJ, The Obama Administration and the Press (2013)', 'https://cpj.org/reports/2013/10/obama-and-the-press-us-leaks-surveillance-post-911/'),
    'us-dadt': ("Obama, discurso ao sancionar o fim do Don't Ask, Don't Tell (2010)",
                'https://www.presidency.ucsb.edu/documents/remarks-signing-the-dont-ask-dont-tell-repeal-act-2010'),
    'us-ledbetter': ('Lilly Ledbetter Fair Pay Act (Pub. L. 111-2), GovInfo', 'https://www.govinfo.gov/content/pkg/PLAW-111publ2/html/PLAW-111publ2.htm'),
    'us-doma': ('Departamento de Justiça dos EUA: declaração sobre o DOMA (2011)',
                'https://www.justice.gov/opa/pr/statement-attorney-general-litigation-involving-defense-marriage-act'),
    'us-eo13535': ('Ordem Executiva 13535 (2010)',
                   'https://www.presidency.ucsb.edu/documents/executive-order-13535-ensuring-enforcement-and-implementation-abortion-restrictions-the'),
    'hrw-libia': ('Human Rights Watch, Unacknowledged Deaths (2012)',
                  'https://www.hrw.org/report/2012/05/13/unacknowledged-deaths/civilian-casualties-natos-air-campaign-libya'),
    'tbij-drones': ('Bureau of Investigative Journalism: a guerra de drones de Obama em números (2017)',
                    'https://www.thebureauinvestigates.com/stories/2017-01-17/obamas-covert-drone-war-in-numbers-ten-times-more-strikes-than-bush'),
    'airwars-ei': ('Airwars: relatório sobre a campanha contra o Estado Islâmico (dez/2016)', 'https://airwars.org/file/99e65786-35c7-4f56-b50f-4fab69076be3'),

    # --- 5: Itália, Mussolini ---
    'it-iri': ('IRI, Wikipedia em italiano', 'https://it.wikipedia.org/wiki/IRI'),
    'it-privat': ('Privatizações do fascismo, Cambridge Journal of Economics (2011)', 'https://ideas.repec.org/a/oup/cambje/v35y2011i5p937-956.html'),
    'it-precos': ('Politica economica fascista, Wikipedia em italiano', 'https://it.wikipedia.org/wiki/Politica_economica_fascista'),
    'it-leis': ('Leggi fascistissime, Wikipedia em italiano', 'https://it.wikipedia.org/wiki/Leggi_fascistissime'),
    'it-camara': ('Camera dei fasci e delle corporazioni, Wikipedia em italiano', 'https://it.wikipedia.org/wiki/Camera_dei_fasci_e_delle_corporazioni'),
    'it-latrao': ('Treccani: Patti lateranensi', 'https://www.treccani.it/enciclopedia/patti-lateranensi_(Diritto-on-line)/'),
    'it-codigo': ('Código Penal italiano de 1930, título X (Brocardi)', 'https://www.brocardi.it/codice-penale/libro-secondo/titolo-x/'),
    'it-solteiros': ('Tassa sul celibato, Wikipedia em italiano', 'https://it.wikipedia.org/wiki/Tassa_sul_celibato'),
    'it-voto': ('Suffragio femminile in Italia, Wikipedia em italiano', 'https://it.wikipedia.org/wiki/Suffragio_femminile_in_Italia'),
    'it-etiopia': ('Second Italo-Ethiopian War, Wikipedia', 'https://en.wikipedia.org/wiki/Second_Italo-Ethiopian_War'),
    'it-adis': ('History Today: o massacre de Adis Abeba', 'https://www.historytoday.com/reviews/addis-ababa-massacre'),
    'it-libia': ('Italian concentration camps in Libya, Wikipedia', 'https://en.wikipedia.org/wiki/Italian_concentration_camps_in_Libya'),
    'it-tribunal': ('Tribunale speciale per la difesa dello Stato, Wikipedia em italiano',
                    'https://it.wikipedia.org/wiki/Tribunale_speciale_per_la_difesa_dello_Stato_(1926-1943)'),
    'it-confino': ('ANPPIA: o confinamento político', 'https://anppia.it/il-confino-politico/'),
    'it-crimes': ('Italian war crimes, Wikipedia', 'https://en.wikipedia.org/wiki/Italian_war_crimes'),
    'ushmm-italia': ('USHMM: Itália', 'https://encyclopedia.ushmm.org/content/en/article/italy'),

    # --- 5: Alemanha, Hitler ---
    'de-precos': ('Tribunal Constitucional Federal da Alemanha, decisão de 22/nov/1994 (sobre o decreto de congelamento de preços de 1936)',
                  'https://www.bundesverfassungsgericht.de/SharedDocs/Entscheidungen/DE/1994/11/rs19941122_1bvr035191.html'),
    'de-reichswerke': ('Reichswerke Hermann Göring, Wikipedia', 'https://en.wikipedia.org/wiki/Reichswerke_Hermann_G%C3%B6ring'),
    'bel2010': ('Germà Bel, Against the mainstream: Nazi privatization in 1930s Germany (2006; Economic History Review, 2010)',
                'https://ideas.repec.org/p/bar/bedcje/2006162.html'),
    'de-plenos': ('USHMM, Enciclopédia do Holocausto: a Lei de Plenos Poderes de 1933', 'https://encyclopedia.ushmm.org/content/en/article/the-enabling-act'),
    'de-partidos': ('Bundestag: 1933, o fim dos partidos', 'https://www.bundestag.de/resource/blob/499298/dcb37a9b8024e8ce692c1b8864d662ef/1933-Das-Ende-der-Parteien.pdf'),
    'ushmm-175': ('USHMM: o parágrafo 175 e a campanha nazista contra a homossexualidade',
                  'https://encyclopedia.ushmm.org/content/en/article/paragraph-175-and-the-nazi-campaign-against-homosexuality'),
    'de-emprestimo': ('Ehestandsdarlehen, Wikipedia em alemão', 'https://de.wikipedia.org/wiki/Ehestandsdarlehen'),
    'de-concordata': ('Reichskonkordat, Wikipedia em alemão', 'https://de.wikipedia.org/wiki/Reichskonkordat'),
    'de-ehegesetz': ('Ehegesetz de 1938, texto (Universidade Johannes Kepler)', 'https://www.jku.at/fileadmin/gruppen/142/Ehegesetz_1938.pdf'),
    'ushmm-nuremberg': ('USHMM: as leis de Nuremberg', 'https://encyclopedia.ushmm.org/content/en/article/nuremberg-laws'),
    'ushmm-numeros': ('USHMM: o número de vítimas do Holocausto e da perseguição nazista',
                      'https://encyclopedia.ushmm.org/content/en/article/documenting-numbers-of-victims-of-the-holocaust-and-nazi-persecution'),
    'yv-faq': ('Yad Vashem: perguntas frequentes', 'https://www.yadvashem.org/holocaust/faqs.html'),
    'ushmm-t4': ('USHMM: o programa de "eutanásia"', 'https://encyclopedia.ushmm.org/content/en/article/euthanasia-program'),
    'ushmm-campos': ('USHMM: os campos nazistas', 'https://encyclopedia.ushmm.org/content/en/article/nazi-camps'),
    'snyder2011': ('Timothy Snyder, Hitler vs. Stalin: Who Killed More? (New York Review of Books, 2011)',
                   'https://www.nybooks.com/articles/2011/03/10/hitler-vs-stalin-who-killed-more/'),
    'ww2museum': ('National WWII Museum: mortes na Segunda Guerra',
                  'https://www.nationalww2museum.org/students-teachers/student-resources/research-starters/research-starters-worldwide-deaths-world-war'),

    # --- 5: URSS, Stálin ---
    'brit-nep': ('Britannica: New Economic Policy', 'https://www.britannica.com/event/New-Economic-Policy-Soviet-history'),
    'brit-planos': ('Britannica: Five-Year Plans', 'https://www.britannica.com/topic/Five-Year-Plans'),
    'brit-coletiv': ('Britannica: collectivization', 'https://www.britannica.com/topic/collectivization'),
    'su-00447': ('NKVD Order No. 00447, Wikipedia', 'https://en.wikipedia.org/wiki/NKVD_Order_No._00447'),
    'su-kruschev': ('Kruschev, discurso secreto ao XX Congresso (1956)', 'https://www.marxists.org/archive/khrushchev/1956/02/24.htm'),
    'su-sodomia': ('Artigo 154-a do Código Penal russo (1934)', 'https://dic.academic.ru/dic.nsf/ruwiki/692882'),
    'su-aborto': ('Seventeen Moments in Soviet History: o fim do aborto legal (1936)', 'https://soviethistory.msu.edu/1936/abolition-of-legal-abortion/'),
    'su-1944': ('Rossiyskaya Gazeta: as leis de família do tempo de guerra (1944)', 'https://rg.ru/2024/07/08/zakony-voennogo-vremeni.html'),
    'su-1929': ('Lei sobre as associações religiosas, 8/abr/1929 (100(0) Schlüsseldokumente)',
                'https://www.1000dokumente.de/?c=dokument_ru&dokument=0007_rel&object=translation&l=ru'),
    'su-const': ('Constituição da URSS de 1936', 'https://www.marxists.org/reference/archive/stalin/works/1936/12/05.htm'),
    'su-fome': ('Soviet famine of 1930-1933, Wikipedia', 'https://en.wikipedia.org/wiki/Soviet_famine_of_1930%E2%80%931933'),
    'brit-holodomor': ('Britannica: Holodomor', 'https://www.britannica.com/event/Holodomor'),
    'cameron': ('Sarah Cameron, The Hungry Steppe (Cornell University Press)', 'https://www.cornellpress.cornell.edu/the-hidden-history-of-the-kazakh-famine/'),
    'ellman2002': ('Michael Ellman, Soviet Repression Statistics: Some Comments (2002)', 'https://sovietinfo.tripod.com/ELM-Repression_Statistics.pdf'),
    'su-excesso': ('Excess mortality in the Soviet Union under Joseph Stalin, Wikipedia', 'https://en.wikipedia.org/wiki/Excess_mortality_in_the_Soviet_Union_under_Joseph_Stalin'),
    'su-gulag': ('Gulag, Wikipedia', 'https://en.wikipedia.org/wiki/Gulag'),
    'su-finlandia': ('Winter War, Wikipedia', 'https://en.wikipedia.org/wiki/Winter_War'),
    'su-katyn': ("CIA, Studies in Intelligence: Stalin's Killing Field", 'https://www.cia.gov/resources/csi/studies-in-intelligence/archives/vol-43-no-3/stalins-killing-field/'),

    # --- 5: Espanha, Franco ---
    'es-renfe': ('Red Nacional de los Ferrocarriles Españoles, Wikipedia em espanhol', 'https://es.wikipedia.org/wiki/Red_Nacional_de_los_Ferrocarriles_Espa%C3%B1oles'),
    'es-ini': ('Instituto Nacional de Industria, Wikipedia em espanhol', 'https://es.wikipedia.org/wiki/Instituto_Nacional_de_Industria'),
    'es-telefonica': ('Telefónica, Wikipedia em espanhol', 'https://es.wikipedia.org/wiki/Telef%C3%B3nica'),
    'es-plano59': ('Plan de Estabilización de 1959, Wikipedia em espanhol', 'https://es.wikipedia.org/wiki/Plan_de_Estabilizaci%C3%B3n_de_1959'),
    'es-divorcio': ('BOE, lei de 23/set/1939 que revoga o divórcio', 'https://www.boe.es/datos/pdfs/BOE/1939/278/A05574-05575.pdf'),
    'es-concordata': ('Concordata entre a Santa Sé e a Espanha (1953)',
                      'https://www.vatican.va/roman_curia/secretariat_state/archivio/documents/rc_seg-st_19530827_concordato-spagna_sp.html'),
    'es-vagos': ('Ley de vagos y maleantes, Wikipedia em espanhol', 'https://es.wikipedia.org/wiki/Ley_de_vagos_y_maleantes'),
    'es-peligrosidad': ('BOE, Lei 16/1970 de periculosidade social', 'https://www.boe.es/buscar/doc.php?id=BOE-A-1970-854'),
    'es-licenca': ('BOE, Lei 14/1975 (fim da licença marital)', 'https://www.boe.es/buscar/doc.php?id=BOE-A-1975-9245'),
    'brit-guerra-civil': ('Britannica: Spanish Civil War', 'https://www.britannica.com/summary/Spanish-Civil-War'),
    'es-franco': ('Francisco Franco, Wikipedia (Payne, Preston)', 'https://en.wikipedia.org/wiki/Francisco_Franco'),
    'es-terror': ('White Terror (Spain), Wikipedia (Casanova)', 'https://en.wikipedia.org/wiki/White_Terror_(Spain)'),
    'es-repressao': ('Represión franquista, Wikipedia em espanhol', 'https://es.wikipedia.org/wiki/Represi%C3%B3n_franquista'),
    'es-campos': ('Francoist concentration camps, Wikipedia', 'https://en.wikipedia.org/wiki/Francoist_concentration_camps'),
    'es-exilio': ('Exilio republicano español, Wikipedia em espanhol', 'https://es.wikipedia.org/wiki/Exilio_republicano_espa%C3%B1ol'),

    # --- 6: Portugal, Salazar ---
    'pt-loc': ('Library of Congress, Portugal: a country study', 'http://countrystudies.us/portugal/64.htm'),
    'pt-economia': ('Economic history of Portugal, Wikipedia', 'https://en.wikipedia.org/wiki/Economic_history_of_Portugal'),
    'pt-vinho': ('Junta Nacional do Vinho, Wikipedia', 'https://pt.wikipedia.org/wiki/Junta_Nacional_do_Vinho'),
    'pt-estadonovo': ('Estado Novo (Portugal), Wikipedia', 'https://en.wikipedia.org/wiki/Estado_Novo_(Portugal)'),
    'pt-concordata': ('Concordat of 1940, Wikipedia', 'https://en.wikipedia.org/wiki/Concordat_of_1940'),
    'pt-aljube': ('Museu do Aljube: lista "Os que ficaram pelo caminho"', 'https://www.museudoaljube.pt/wp-content/uploads/2020/04/MARL_Lista_Os-que-ficaram-pelo-caminho.pdf'),
    'pt-tarrafal': ('Campo de Concentração do Tarrafal, Wikipedia', 'https://pt.wikipedia.org/wiki/Campo_de_Concentra%C3%A7%C3%A3o_do_Tarrafal'),
    'pt-delgado': ('Humberto Delgado, Wikipedia', 'https://pt.wikipedia.org/wiki/Humberto_Delgado'),
    'pt-presos': ('Memorial 2019: presos e perseguidos políticos', 'https://memorial2019.org/presos-e-perseguidos-politicos'),
    'pt-guerra': ('Portuguese Colonial War, Wikipedia', 'https://en.wikipedia.org/wiki/Portuguese_Colonial_War'),
    'ao-guerra': ('Angolan War of Independence, Wikipedia', 'https://en.wikipedia.org/wiki/Angolan_War_of_Independence'),

    # --- 6: Chile, Pinochet ---
    'cl-dl3500': ('Decreto-lei 3.500 (1980), LeyChile', 'https://www.leychile.cl/Consulta/obtxml?opt=7&idNorma=7147'),
    'cl-dl1350': ('Decreto-lei 1.350 (1976, Codelco), LeyChile', 'https://www.leychile.cl/Consulta/obtxml?opt=7&idNorma=6578'),
    'cl-bcch': ('Banco Central do Chile, documento de trabalho 57',
                'https://www.bcentral.cl/documents/33528/133326/DTBC_57.pdf/8cc3195c-f838-f2d0-6a75-5052adbb3e2c?t=1693236872076'),
    'cl-ditadura': ('Dictadura militar (Chile), Wikipedia em espanhol', 'https://es.wikipedia.org/wiki/Dictadura_militar_%28Chile%29'),
    'cl-dl27': ('Decreto-lei 27 (1973), LeyChile', 'https://www.leychile.cl/Consulta/obtxml?opt=7&idNorma=209763'),
    'cl-dina': ('National Security Archive: o decreto-lei 521 cria a DINA',
                'https://nsarchive.gwu.edu/document/32158-document-1-chilean-interior-ministry-decreto-ley-521-crea-la-direccion-de'),
    'cl-bcn': ('Biblioteca do Congresso do Chile: o período 1973-1990', 'https://www.bcn.cl/historiapolitica/hitos_periodo/detalle_periodo.html?per=1973-1990'),
    'cl-18826': ('Lei 18.826 (1989), LeyChile', 'https://www.leychile.cl/Consulta/obtxml?opt=7&idNorma=30202'),
    'cl-const80': ('Constituição do Chile de 1980, LeyChile', 'https://www.leychile.cl/Consulta/obtxml?opt=7&idNorma=242302'),
    'cl-18802': ('Lei 18.802 (1989), LeyChile', 'https://www.leychile.cl/Consulta/obtxml?opt=7&idNorma=30179'),
    'cl-rettig': ('Rettig Report, Wikipedia', 'https://en.wikipedia.org/wiki/Rettig_Report'),
    'cl-valech': ('Valech Report, Wikipedia', 'https://en.wikipedia.org/wiki/Valech_Report'),

    # --- 6: Argentina, junta ---
    'ar-argendata': ('Argendata: gasto público', 'https://argendata.fund.ar/topico/gasto-publico/'),
    'ar-mhoz': ('José Alfredo Martínez de Hoz, Wikipedia', 'https://en.wikipedia.org/wiki/Jos%C3%A9_Alfredo_Mart%C3%ADnez_de_Hoz'),
    'ar-divida': ('Estatización de la deuda privada, Wikipedia em espanhol', 'https://es.wikipedia.org/wiki/Estatizaci%C3%B3n_de_la_deuda_privada'),
    'ar-proceso': ('National Reorganization Process, Wikipedia', 'https://en.wikipedia.org/wiki/National_Reorganization_Process'),
    'ar-21745': ('Lei 21.745 (1978), governo argentino', 'https://www.argentina.gob.ar/normativa/nacional/ley-21745-65159/texto'),
    'ar-21950': ('Lei 21.950 (1979), governo argentino', 'https://www.argentina.gob.ar/normativa/nacional/norma-196543/texto'),
    'ar-conadep': ('CONADEP, Wikipedia', 'https://en.wikipedia.org/wiki/National_Commission_on_the_Disappearance_of_Persons'),
    'ar-601': ('National Security Archive: o Exército argentino contava 22 mil mortos e desaparecidos', 'https://nsarchive2.gwu.edu/NSAEBB/NSAEBB185/index.htm'),
    'ar-ccd': ('Centro clandestino de detención (Argentina), Wikipedia em espanhol', 'https://es.wikipedia.org/wiki/Centro_clandestino_de_detenci%C3%B3n_(Argentina)'),
    'malvinas': ('Falklands War, Wikipedia', 'https://en.wikipedia.org/wiki/Falklands_War'),

    # --- 7: Rússia, Lênin ---
    'ru-bancos': ('Seventeen Moments in Soviet History: a estatização dos bancos',
                  'https://soviethistory.msu.edu/1917/economic-apparatus/economic-apparatus-texts/nationalization-of-banks/'),
    'ru-comercio': ('Decreto de 22/abr/1918 sobre o comércio exterior (marxists.org)', 'https://www.marxists.org/history/ussr/events/revolution/documents/1918/04/22.htm'),
    'ru-comunismo': ('War communism, Wikipedia', 'https://en.wikipedia.org/wiki/War_communism'),
    'ru-constituinte': ('Russian Constituent Assembly, Wikipedia', 'https://en.wikipedia.org/wiki/Russian_Constituent_Assembly'),
    'ru-tcheka': ('Cheka, Wikipedia', 'https://en.wikipedia.org/wiki/Cheka'),
    'ru-familia': ('Encyclopedia.com: o Código da Família de 1918',
                   'https://www.encyclopedia.com/history/encyclopedias-almanacs-transcripts-and-maps/family-code-marriage-family-and-guardianship'),
    'ru-igreja': ('Decree on Separation of Church and State, Wikipedia', 'https://en.wikipedia.org/wiki/Decree_on_Separation_of_Church_and_State'),
    'ru-lgbt': ('LGBT history in Russia, Wikipedia', 'https://en.wikipedia.org/wiki/LGBT_history_in_Russia'),
    'brit-terror': ('Britannica: Red Terror', 'https://www.britannica.com/topic/Red-Terror'),
    'ru-terror': ('Red Terror, Wikipedia', 'https://en.wikipedia.org/wiki/Red_Terror'),
    'ru-tambov': ('Tambov Rebellion, Wikipedia', 'https://en.wikipedia.org/wiki/Tambov_Rebellion'),
    'ru-kronstadt': ('Kronstadt rebellion, Wikipedia', 'https://en.wikipedia.org/wiki/Kronstadt_rebellion'),
    'ru-fome': ('Universidade de Warwick: a fome russa de 1921-1922', 'https://warwick.ac.uk/services/library/mrc/collections/digital/russia/famine/'),
    'ru-georgia': ('Red Army invasion of Georgia, Wikipedia', 'https://en.wikipedia.org/wiki/Red_Army_invasion_of_Georgia'),

    # --- 7: Turquia, Atatürk ---
    'tr-tekel': ('Tekel, Wikipedia', 'https://en.wikipedia.org/wiki/Tekel'),
    'tr-ferrovias': ('Turkish State Railways, Wikipedia', 'https://en.wikipedia.org/wiki/Turkish_State_Railways'),
    'tr-economia': ('Economic history of Turkey, Wikipedia', 'https://en.wikipedia.org/wiki/Economic_history_of_Turkey'),
    'tr-kemalismo': ('Kemalism, Wikipedia', 'https://en.wikipedia.org/wiki/Kemalism'),
    'tr-esmirna': ('Izmir Economic Congress, Wikipedia', 'https://en.wikipedia.org/wiki/%C4%B0zmir_Economic_Congress'),
    'tr-partido': ('Progressive Republican Party (Turkey), Wikipedia', 'https://en.wikipedia.org/wiki/Progressive_Republican_Party_(Turkey)'),
    'tr-tribunais': ('Independence Tribunal, Wikipedia', 'https://en.wikipedia.org/wiki/Independence_Tribunal'),
    'tr-historia': ('History of the Republic of Turkey, Wikipedia', 'https://en.wikipedia.org/wiki/History_of_the_Republic_of_Turkey'),
    'tr-laico': ('Secularism in Turkey, Wikipedia', 'https://en.wikipedia.org/wiki/Secularism_in_Turkey'),
    'tr-mulher': ('Women in Turkey, Wikipedia', 'https://en.wikipedia.org/wiki/Women_in_Turkey'),
    'tr-voto': ("Women's suffrage in Turkey, Wikipedia", 'https://en.wikipedia.org/wiki/Women%27s_suffrage_in_Turkey'),
    'tr-said': ('Sheikh Said rebellion, Wikipedia', 'https://en.wikipedia.org/wiki/Sheikh_Said_rebellion'),
    'tr-zilan': ('Zilan massacre, Wikipedia', 'https://en.wikipedia.org/wiki/Zilan_massacre'),
    'tr-dersim': ('Dersim massacre, Wikipedia', 'https://en.wikipedia.org/wiki/Dersim_massacre'),

    # --- 7: China, Mao ---
    'brit-salto': ('Britannica: Great Leap Forward', 'https://www.britannica.com/event/Great-Leap-Forward'),
    'cn-plano': ('First five-year plan (China), Wikipedia', 'https://en.wikipedia.org/wiki/First_five-year_plan_(China)'),
    'cn-salto': ('Great Leap Forward, Wikipedia', 'https://en.wikipedia.org/wiki/Great_Leap_Forward'),
    'cn-cnp': ("3rd National People's Congress, Wikipedia", 'https://en.wikipedia.org/wiki/3rd_National_People%27s_Congress'),
    'cn-const54': ('1954 Constitution of China, Wikipedia', 'https://en.wikipedia.org/wiki/1954_Constitution_of_China'),
    'cn-liu': ('Liu Shaoqi, Wikipedia', 'https://en.wikipedia.org/wiki/Liu_Shaoqi'),
    'cn-casamento': ('ChinaKnowledge: a Lei do Casamento de 1950', 'http://www.chinaknowledge.de/History/PRC/prc-event-marriagelaw.html'),
    'cn-velhos': ('Four Olds, Wikipedia', 'https://en.wikipedia.org/wiki/Four_Olds'),
    'cn-aborto': ('Abortion in China, Wikipedia', 'https://en.wikipedia.org/wiki/Abortion_in_China'),
    'cn-reforma': ('Land Reform Movement, Wikipedia', 'https://en.wikipedia.org/wiki/Land_Reform_Movement'),
    'cn-contra': ('Campaign to Suppress Counterrevolutionaries, Wikipedia', 'https://en.wikipedia.org/wiki/Campaign_to_Suppress_Counterrevolutionaries'),
    'cn-fome': ('Great Chinese Famine, Wikipedia', 'https://en.wikipedia.org/wiki/Great_Chinese_Famine'),
    'cn-walder': ('Andrew Walder, Stanford: mortes na Revolução Cultural', 'https://aparc.fsi.stanford.edu/china/node/24671'),
    'cn-direitistas': ('Anti-Rightist Campaign, Wikipedia', 'https://en.wikipedia.org/wiki/Anti-Rightist_Campaign'),
    'cn-tibete': ("Annexation of Tibet by the People's Republic of China, Wikipedia", 'https://en.wikipedia.org/wiki/Annexation_of_Tibet_by_the_People%27s_Republic_of_China'),
    'cn-india': ('Sino-Indian War, Wikipedia', 'https://en.wikipedia.org/wiki/Sino-Indian_War'),

    # --- 7: Cuba, Fidel ---
    'cu-fidel': ('Fidel Castro, Wikipedia', 'https://en.wikipedia.org/wiki/Fidel_Castro'),
    'cu-ofensiva': ('Revolutionary Offensive, Wikipedia', 'https://en.wikipedia.org/wiki/Revolutionary_Offensive'),
    'cu-racionamento': ('Rationing in Cuba, Wikipedia', 'https://en.wikipedia.org/wiki/Rationing_in_Cuba'),
    'cu-mulher': ('Women in Cuba, Wikipedia', 'https://en.wikipedia.org/wiki/Women_in_Cuba'),
    'cu-aborto': ('Abortion in Cuba, Wikipedia', 'https://en.wikipedia.org/wiki/Abortion_in_Cuba'),
    'cu-religiao': ('Religion in Cuba, Wikipedia', 'https://en.wikipedia.org/wiki/Religion_in_Cuba'),
    'cu-lgbt': ('LGBTQ rights in Cuba, Wikipedia', 'https://en.wikipedia.org/wiki/LGBTQ_rights_in_Cuba'),
    'cu-dh': ('Human rights in Cuba, Wikipedia', 'https://en.wikipedia.org/wiki/Human_rights_in_Cuba'),
    'cu-archive': ('Maria Werlau (Cuba Archive), depoimento ao Congresso dos EUA (2016)',
                   'https://docs.house.gov/meetings/fa/fa16/20160713/105207/hhrg-114-fa16-wstate-werlaum-20160713.pdf'),

    # --- 7: Camboja, Khmer Vermelho ---
    'kh-polpot': ('Pol Pot, Wikipedia', 'https://en.wikipedia.org/wiki/Pol_Pot'),
    'kh-kampuchea': ('Democratic Kampuchea, Wikipedia', 'https://en.wikipedia.org/wiki/Democratic_Kampuchea'),
    'kh-khmer': ('Khmer Rouge, Wikipedia', 'https://en.wikipedia.org/wiki/Khmer_Rouge'),
    'kh-yale': ('Universidade Yale: Cambodian Genocide Program', 'https://macmillan.yale.edu/node/3003267/cambodian-genocide-program'),
    'kh-genocidio': ('Cambodian genocide, Wikipedia (Kiernan, Heuveline)', 'https://en.wikipedia.org/wiki/Cambodian_genocide'),
    'kh-vietna': ('Cambodian-Vietnamese War, Wikipedia', 'https://en.wikipedia.org/wiki/Cambodian%E2%80%93Vietnamese_War'),

    # --- 8: Peru, Fujimori ---
    'pe-choque': ('Fujishock, Wikipedia em espanhol', 'https://es.wikipedia.org/wiki/Fujishock'),
    'pe-cpt': ('Compañía Peruana de Teléfonos, Wikipedia em espanhol', 'https://es.wikipedia.org/wiki/Compa%C3%B1%C3%ADa_Peruana_de_Tel%C3%A9fonos'),
    'pe-dl25418': ('Decreto-lei 25418 (1992), NATLEX/OIT', 'https://natlex.ilo.org/dyn/natlex2/r/natlex/fe/details?p3_isn=28771'),
    'pe-autogolpe': ('Autogolpe de Estado de Perú de 1992, Wikipedia em espanhol', 'https://es.wikipedia.org/wiki/Autogolpe_de_Estado_de_Per%C3%BA_de_1992'),
    'pe-fujimori': ('Alberto Fujimori, Wikipedia em espanhol', 'https://es.wikipedia.org/wiki/Alberto_Fujimori'),
    'pe-vacancia': ('Congresso do Peru: resolução de vacância por incapacidade moral (2000)',
                    'https://www.congreso.gob.pe/Docs/participacion/museo/congreso/files/mensajes/1981-2000/files/resolucionlegislativa-incapacidadmoral-2000-af.pdf'),
    'pe-26530': ('Lei 26.530 (1995), Justia Peru', 'https://docs.peru.justia.com/federales/leyes/26530-sep-9-1995.pdf'),
    'pe-ideele': ('Revista Ideele: a anticoncepção cirúrgica no Peru de Fujimori',
                  'https://www.revistaideele.com/2021/08/24/el-peru-de-fujimori-historia-de-la-aplicacion-de-anticoncepcion-quirurgica-voluntaria/'),
    'pe-cp91': ('Código Penal do Peru de 1991 (CEPAL)', 'https://oig.cepal.org/sites/default/files/1991_per_dl635.pdf'),
    'pe-26770': ('Lei 26.770 (1997), Justia Peru', 'https://docs.peru.justia.com/federales/leyes/26770-apr-11-1997.pdf'),
    'pe-cotas': ('Lei 26.859 (Lei Orgânica de Eleições, 1997), JNE',
                 'https://portal.jne.gob.pe/portal_documentos/files/informacionlegal/Constitucin%20y%20Leyes1/Ley%20Organica%20de%20Elecciones,%20Ley%20N%2026859.pdf'),
    'pe-const93': ('Constituição do Peru de 1993 (Georgetown)', 'https://pdba.georgetown.edu/Constitutions/Peru/per93.html'),
    'pe-idehpucp': ('IDEHPUCP: relatório sobre as esterilizações forçadas',
                    'https://cdn01.pucp.education/idehpucp/wp-content/uploads/2017/06/28155647/pub065informeesterilizacionesforzadas.pdf'),
    'pe-france24': ('France 24: começa o processo das esterilizações forçadas (2021)',
                    'https://www.france24.com/es/am%C3%A9rica-latina/20211211-peru-fujimori-esterilizaciones-forzadas'),
    'pe-barriosaltos': ('Corte Interamericana de Direitos Humanos, caso Barrios Altos', 'https://www.corteidh.or.cr/docs/casos/articulos/Seriec_75_esp.pdf'),
    'pe-cantuta': ('Masacre de La Cantuta, Wikipedia em espanhol', 'https://es.wikipedia.org/wiki/Masacre_de_La_Cantuta'),

    # --- fora do cubo ---
    'it-eni': ('Lei 136 de 10/fev/1953 (ENI), Gazzetta Ufficiale', 'https://www.gazzettaufficiale.it/eli/id/1953/03/27/053U0136/sg'),
    'it-lamalfa': ('Dizionario dell\'integrazione europea: Ugo La Malfa', 'https://www.dizie.eu/dizionario/la-malfa-ugo/'),
    'it-art7': ('UAAR: o PSI e o artigo 7 da Constituição', 'https://www.uaar.it/uaar/documenti/137.html/'),
    'it-dec74': ('Decreto legislativo luogotenenziale 74 de 10/mar/1946',
                 'https://s3.eu-west-1.amazonaws.com/dellarepubblica.it/Protagonismo%20donne/voto%20alle%20donne/Decreto_legislativo_luogotenenziale_n._74_del_10_marzo_1946.pdf'),
    'it-truffa': ('Il Post: a "legge truffa" de 1953', 'https://www.ilpost.it/2023/03/31/legge-elettorale-truffa/'),
    'uk-privat': ('Câmara dos Comuns, Research Paper 14/61: privatizações', 'https://researchbriefings.files.parliament.uk/documents/RP14-61/RP14-61.pdf'),
    'uk-s28': ('Arquivos Nacionais do Reino Unido: as origens da Seção 28', 'https://www.nationalarchives.gov.uk/explore-the-collection/stories/origins-section-28/'),
    'uk-era88': ('Education Reform Act 1988, legislation.gov.uk', 'https://www.legislation.gov.uk/ukpga/1988/39/contents/enacted'),
    'uk-mfpa': ('Hansard, Câmara dos Lordes, 21/nov/1983 (divórcio)', 'https://api.parliament.uk/historic-hansard/lords/1983/nov/21/matrimonial-and-family-proceedings-bill'),
    'uk-flra': ('Family Law Reform Act 1987, legislation.gov.uk', 'https://www.legislation.gov.uk/ukpga/1987/42/enacted'),
    'uk-s46': ('Education (No. 2) Act 1986, seção 46, legislation.gov.uk', 'https://www.legislation.gov.uk/ukpga/1986/61/section/46/enacted'),
    'uk-imposto': ('Hansard, 15/mar/1988: tributação separada da esposa', 'https://api.parliament.uk/historic-hansard/commons/1988/mar/15/independent-taxation-and-tax-penalties'),
    'ru-1993': ('UPI, 28/mai/1993: a Rússia legaliza a homossexualidade', 'https://www.upi.com/Archives/1993/05/28/Russia-legalizes-homosexuality/8803738561600/'),
    'ru-1997': ('Law on Freedom of Conscience and Religious Associations, Wikipedia',
                'https://en.wikipedia.org/wiki/Law_on_Freedom_of_Conscience_and_Religious_Associations'),
    'ru-familia95': ('Family Code of Russia, Wikipedia', 'https://en.wikipedia.org/wiki/Family_Code_of_Russia'),
    'ru-crise93': ('Verfassungsblog: a crise constitucional de 1993', 'https://verfassungsblog.de/paving-the-way-for-violence/'),
    'gt-indice': ('Índice das leis da Guatemala (archive.org)', 'https://archive.org/stream/indicedelasleyes00dmigguat/indicedelasleyes00dmigguat_djvu.txt'),
    'gt-const79': ('Constitución de Guatemala de 1879, Wikipedia em espanhol', 'https://es.wikipedia.org/wiki/Constituci%C3%B3n_de_Guatemala_de_1879'),
    'gt-barrios': ('Justo Rufino Barrios, Wikipedia em espanhol', 'https://es.wikipedia.org/wiki/Justo_Rufino_Barrios'),
    'es-catalunha': ('Revolutionary Catalonia, Wikipedia', 'https://en.wikipedia.org/wiki/Revolutionary_Catalonia'),
}
